### PR TITLE
fix arity render_show

### PR DESCRIPTION
**Pull request by clairton**

### CODE REVIEW

**Comment by beerlington** [comment]
What's the reason for this change? Can you please also update the docs? They are referencing `render_index/3`.

**Comment by clairton** [comment]
Hi @beerlington.
The `render_index/3` continue with the same arity, the `render_show/2` is fixed to be like `render_update/2` because they render a record while `render_index/3` render a collection.

**Comment by beerlington** [comment]
@clairton this is the line I was referring to when I asked about updating the docs https://github.com/vt-elixir/ja_resource/blob/cd6645516ba11202a93912bfc3cab9ae421de623/lib/ja_resource/show.ex#L18

**Comment by clairton** [comment]
it's true @beerlington, thanks.

**Comment by beerlington** [comment]
Thanks!

**Pull request merged**
