### PR TITLE
Support Phoenix 1.4 with Ecto 3.0

### PR DESCRIPTION
**Pull request by ericdude4**
Here is a test passing PR which uses Ecto 3.0. This is all that is required to be compatible with Phoenix 1.4.

None of the breaking changes in Ecto seem to affect ja_resource. All I did was update the deps on ja_resource.

https://github.com/vt-elixir/ja_resource/issues/81

### CODE REVIEW

**Comment by ericdude4** [comment]
Seems Ecto requires Elixir 1.4

**Comment by joshuataylor** [comment]
Would `~> 2.0 or ~> 3.0` be acceptable, to also support 2.0?

**Comment by ericdude4** [comment]
This branch was never merged... what do you mean?

**Comment by RaphSfeir** [comment]
Is this still in progress or planned for a merge? The upgrade to 1.4 would be great.

**Comment by ericdude4** [comment]
@RaphSfeir the build failed since Ecto 3 isn't compatibe with Elixir 1.2.0 which the build check here requires. I forked this repo for my own Phoenix 1.4 project and its been working well.

**Comment by psteininger** [comment]
@ericdude4  thanks for the PR

**Comment by ericdude4** [comment]
@psteininger Current Ecto version is 3.3.1. When I made this PR it was 3.0. Current version also requires Elixir "\~> 1.6". Do we want to explore making a release for the current state of this repository, then bumping the version up to 1.0.0 and require Elixir  "~> 1.6" with the most recent version of Ecto? I love this package and feel that it deserves a 1.0 release :)

**Comment by psteininger** [comment]
@ericdude4 I am open to anything. I, too, really like this project and it's the second time I am using it in production. 

Speaking of dependencies, could you provide feedback on #83 in regards to Elixir and OTP versions we should include in a matrix? I was thinking that using the latest 3 for Elixir (1.9, 1.8, 1.7) might be sufficient and the corresponding OTP versions (I think 21 and 22) would be enough.

**Comment by ericdude4** [comment]
@psteininger Since I assume we are going to set the major version to 1.x, we can make the dependencies as up-to-date as we want. I would say we follow suit of the latest Phoenix 1.4 dependencies (provided that it doesn't break anything) since that will be the environment that most new projects will already have. 

Currently, Phoenix 1.4 supports Elixir 1.5 and OTP 19. The Phoenix 1.5.0-dev build supports Elixir 1.6, which itself requires OTP 19. I would say we should be compatible with the most recent stable release of Phoenix. Elixir ~> 1.7 is a higher requirement than even the development build of Phoenix. Also, Elixir 1.10 just released :) https://elixir-lang.org/blog/2020/01/27/elixir-v1-10-0-released/

The requirements for Phoenix 1.4 that I think we should match in this repository are:
Elixir ~>1.5
OTP 19
Ecto ~>3.0

**Pull request merged**
