### PR TITLE
Add error handling for index actions

### PR DESCRIPTION
**Pull request by totallymike**

### CODE REVIEW

**Comment by alanpeabody** [comment]
:+1:

**Comment by totallymike** [comment]
I can't merge it :D

**Comment by alanpeabody** [comment]
@totallymike my bad, I thought when I made you a member you got push access. I have resolved it and you should have push now.

**Comment by totallymike** [comment]
@alanpeabody No problem 😄 . I suspected that was the case. Thanks for setting me up!

**Pull request merged**
